load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "pipeline",
    srcs = ["pipeline.go"],
    importpath = "github.com/stefanpenner/github-ci-demo/internal/pipeline",
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "pipeline_test",
    srcs = ["pipeline_test.go"],
    embed = [":pipeline"],
)
